using System.Collections.ObjectModel;

namespace P4G.SaveTool.Catalog;

public static partial class P4GCatalog
{
    private static readonly string[] PersonasNames =
    [
        "000",
        "Izanagi",
        "Tzitzimitl",
        "Flauros",
        "Loki",
        "Ishtar",
        "Pyro Jack",
        "Jack Frost",
        "Scathach",
        "Rangda",
        "Hachiman",
        "Cu Chulainn",
        "Ose",
        "Kusi Mitama",
        "Apsaras",
        "Ardha",
        "Parvati",
        "Kikuri-Hime",
        "Zaou-Gongen",
        "Sarasvati",
        "Yatsufusa",
        "Cybele",
        "Sraosha",
        "Neko Shogun",
        "Kali",
        "Obariyon",
        "Ukobach",
        "Lamia",
        "Odin",
        "King Frost",
        "Oukuninushi",
        "Undine",
        "Sylph",
        "Forneus",
        "Alraune",
        "Mithra",
        "Daisoujou",
        "Ananta",
        "Futsunushi",
        "Triglav",
        "Raphael",
        "Titania",
        "Oberon",
        "02B",
        "Sandman",
        "Leanan Sidhe",
        "Pixie",
        "Uriel",
        "Surt",
        "Throne",
        "Ares",
        "Titan",
        "034",
        "Ara Mitama",
        "Valkyrie",
        "Melchizedek",
        "Dominion",
        "Siegfried",
        "Virtue",
        "Power",
        "Archangel",
        "Angel",
        "Hitokotonusi",
        "Ippon-Datara",
        "Nebiros",
        "Decarabia",
        "Belphegor",
        "Yomotsu-Shikome",
        "Vetala",
        "Norn",
        "Atropos",
        "Pazuzu",
        "Lachesis",
        "Saki Mitama",
        "Eligor",
        "Clotho",
        "Fortuna",
        "Thor",
        "Mokoi",
        "Abaddon",
        "Belial",
        "Hanuman",
        "Yoshitsune",
        "Mahakala",
        "Attis",
        "Vasuki",
        "Orthrus",
        "Tam Lin",
        "Jinn",
        "Mada",
        "White Rider",
        "Alice",
        "Seth",
        "Mot",
        "Samael",
        "Gdon",
        "Gorgon",
        "Dis",
        "Michael",
        "Byakko",
        "Suzaku",
        "Seiryuu",
        "Nigi Mitama",
        "Genbu",
        "Beelzebub",
        "Mother Harlot",
        "Shiki-Ouji",
        "Lilith",
        "Incubus",
        "Succubus",
        "Lilim",
        "Phoenix",
        "Shiva",
        "Masakado",
        "Ikusa",
        "Yamatano-Orochi",
        "Anzu",
        "Helel",
        "Sandalphon",
        "Black Frost",
        "Garuda",
        "Sui-ki",
        "Ganesha",
        "Isis",
        "Cerberus",
        "Fuu-ki",
        "Setanta",
        "Girimehkala",
        "Nozuchi",
        "Legion",
        "Berith",
        "Saturnus",
        "Vishnu",
        "Barong",
        "Andra",
        "Horus",
        "Narasimha",
        "Senri",
        "Kin-ki",
        "Asura",
        "Metatron",
        "Satan",
        "Gabriel",
        "Hokuto Seikun",
        "Trumpeter",
        "Anubis",
        "Nata Taishi",
        "Ongyo-ki",
        "High Pixie",
        "Yaksini",
        "Xiezhai",
        "Thoth",
        "Cu Sith",
        "Mothman",
        "Oni",
        "Makami",
        "Rakshasa",
        "Matador",
        "Hell Biker",
        "Taowu",
        "Taotie",
        "Pabilsag",
        "Mara",
        "Kartikeya",
        "Baal Zebul",
        "Suparna",
        "Lucifer",
        "Orobas",
        "Atavaka",
        "Hariti",
        "Skadi",
        "Unicorn",
        "Omoikane",
        "Shiisaa",
        "Principality",
        "Kurama Tengu",
        "Yurlungur",
        "Kaiwan",
        "Jatayu",
        "Slime",
        "0B4",
        "0B5",
        "Arahabaki",
        "Hua Po",
        "Alilat",
        "Kohryu",
        "Ghoul",
        "Queen Mab",
        "Ganga",
        "Izanagi-no-Okami",
        "Niddhoggr",
        "Yatagarasu",
        "Jiraiya",
        "Susano-O",
        "Tomoe",
        "Suzuka Gongen",
        "Konohana Sakuya",
        "Amaterasu",
        "Take-Mikazuchi",
        "Rokuten Maoh",
        "Himiko",
        "Kanzeon",
        "Kintoki-Douji",
        "Kamui",
        "Sukuna-Hikona",
        "Yamato Takeru",
        "Magatsu-Izanagi",
        "Takehaya Susano-o",
        "Haraedo-no-Okami",
        "Sumeo-Okami",
        "Takeji Zaiten",
        "Kouzeon",
        "Kamui-Moshiri",
        "Yamato Sumeragi",
        "0D6",
        "0D7",
        "0D8",
        "0D9",
        "0DA",
        "0DB",
        "0DC",
        "0DD",
        "0DE",
        "0DF",
        "Black Izanami",
        "Okami",
        "ÇñÇóÇºÇôÇò",
        "ÇñÇóÇºÇöÇò",
        "ÇñÇóÇºÇòÇò",
        "ÇñÇóÇºÇûÇò",
        "ÇñÇóÇºÇùÇò",
        "ÇñÇóÇºÇÿÇò",
        "Kaguya",
        "Pale Rider",
        "Take-Minakata",
        "Narcissus",
        "Kumbhanda",
        "Gurr",
        "Baphomet",
        "Loa",
        "Chernobog",
        "Quetzalcoatl",
        "Ame-no-Uzume",
        "Seiten Taisei",
        "Kingu",
        "Kushinada",
        "Sati",
        "Raja Naga",
        "Laksmi",
        "Magatsu-Izanagi",
    ];
    public static ReadOnlyCollection<PersonaCatalogEntry> Personas { get; } = CreateIndexedEntries(PersonasNames, static (id, name) => new PersonaCatalogEntry((ushort)id, name));
    public static ReadOnlyDictionary<ushort, PersonaCatalogEntry> PersonasById { get; } = CreateLookup(Personas, static entry => entry.Id);

    private static readonly string[] SkillsNames =
    [
        "Blank",
        "Agi",
        "Agilao",
        "Agidyne",
        "Maragi",
        "Maragion",
        "Maragidyne",
        "Prominence",
        "Ragnarok",
        "Immortal Flame",
        "Tiny Soul Tomato",
        "Tetracorn",
        "Run Amok",
        "Shake Off",
        "Garu",
        "Garula",
        "Garudyne",
        "Magaru",
        "Magarula",
        "Magarudyne",
        "Divine Vacuum",
        "Panta Rhei",
        "Hiranya Cabbage",
        "Cry of Denial",
        "Hot Lightning",
        "Draining Fog",
        "Bufu",
        "Bufula",
        "Bufudyne",
        "Mabufu",
        "Mabufula",
        "Mabufudyne",
        "Cocytus Pain",
        "Niflheim",
        "Bloody Rain",
        "Red Paprika",
        "Enclosure Shell",
        "Hot Lightning",
        "Shell of Denial",
        "Zio",
        "Zionga",
        "Ziodyne",
        "Mazio",
        "Mazionga",
        "Maziodyne",
        "Jihad",
        "Thunder Reign",
        "Bead Melon",
        "Mid Soul Tomato",
        "Big Soul Tomato",
        "Makaracorn",
        "Megido",
        "Megidola",
        "Megidolaon",
        "Last Resort",
        "Black Viper",
        "Morning Star",
        "White Paprika",
        "Blue Paprika",
        "Green Paprika",
        "Blank",
        "Hama",
        "Hamaon",
        "Mahama",
        "Mahamaon",
        "Eternal White",
        "God's Judgment",
        "Samsara",
        "Blank",
        "Blank",
        "Blank",
        "Blank",
        "Mudo",
        "Mudoon",
        "Mamudo",
        "Mamudoon",
        "Eternal Black",
        "Demonic Judgment",
        "Die for Me!",
        "Blank",
        "Blank",
        "Blank",
        "Blank",
        "Pulinpa",
        "Tentarafoo",
        "Evil Touch",
        "Evil Smile",
        "Ghastly Wail",
        "Balzac",
        "Valiant Dance",
        "Poisma",
        "Poison Mist",
        "Soul Break",
        "Anima Freeze",
        "Enervation",
        "Old One",
        "Galgalim Eyes",
        "Makajam",
        "Foolish Whisper",
        "Foul Breath",
        "Stagnant Air",
        "Life Drain",
        "Spirit Drain",
        "Life Leech",
        "Spirit Leech",
        "Judgement",
        "Balzac",
        "Last Resort",
        "Last Resort",
        "Kamui Miracle",
        "Kamui Miracle",
        "Kamui Miracle",
        "Kamui Miracle",
        "Kamui Miracle",
        "Kamui Miracle",
        "Kamui Miracle",
        "Kamui Miracle",
        "Kamui Miracle",
        "Blank",
        "Elemental Break",
        "Bash",
        "Cleave",
        "Assault Dive",
        "Sonic Punch",
        "Double Fangs",
        "Kill Rush",
        "Swift Strike",
        "Twin Shot",
        "Fatal End",
        "Mighty Swing",
        "Torrent Shot",
        "Heat Wave",
        "Gigantic Fist",
        "Blade of Fury",
        "Deathbound",
        "Arrow Rain",
        "Akasha Arts",
        "Tempest Slash",
        "Heaven's Blade",
        "Myriad Arrows",
        "God's Hand",
        "Pralaya",
        "Primal Force",
        "Vorpal Blade",
        "Power Slash",
        "Gale Slash",
        "Brave Blade",
        "Herculean Strike",
        "Vicious Strike",
        "Single Shot",
        "Skewer",
        "Poison Skewer",
        "Poison Arrow",
        "Blight",
        "Virus Wave",
        "Skull Cracker",
        "Mind Slice",
        "Hysterical Slap",
        "Crazy Chain",
        "Muzzle Shot",
        "Seal Bomb",
        "Arm Chopper",
        "Atom Smasher",
        "Cell Breaker",
        "Mustard Bomb",
        "Brain Shake",
        "Navas Nebula",
        "Golden Right",
        "Black Spot",
        "Rainy Death",
        "Hassou Tobi",
        "Rampage",
        "Aeon Rain",
        "Agneyastra",
        "Cruel Attack",
        "Vile Assault",
        "Rampage",
        "Attack Up Support",
        "Guard Up Support",
        "Agility Up Support",
        "Charge Support",
        "HP Recovery Support",
        "SP Recovery Support",
        "Blank",
        "Blank",
        "Blank",
        "Blank",
        "Blank",
        "Blank",
        "Blank",
        "Blank",
        "Blank",
        "Dia",
        "Diarama",
        "Diarahan",
        "Media",
        "Mediarama",
        "Mediarahan",
        "Salvation",
        "Patra",
        "Me Patra",
        "Re Patra",
        "Posumudi",
        "Mutudi",
        "Enradi",
        "Tirundi",
        "Nervundi",
        "Energy Shower",
        "Amrita",
        "Recarm",
        "Samarecarm",
        "Tarunda",
        "Matarunda",
        "Sukunda",
        "Masukunda",
        "Rakunda",
        "Marakunda",
        "Dekunda",
        "Tarukaja",
        "Matarukaja",
        "Sukukaja",
        "Masukukaja",
        "Rakukaja",
        "Marakukaja",
        "Dekaja",
        "Heat Riser",
        "Debilitate",
        "Power Charge",
        "Mind Charge",
        "Tetrakarn",
        "Makarakarn",
        "Tetra Break",
        "Makara Break",
        "Tetraja",
        "Rebellion",
        "Revolution",
        "Fire Break",
        "Ice Break",
        "Wind Break",
        "Elec Break",
        "Red Wall",
        "White Wall",
        "Blue Wall",
        "Green Wall",
        "Trafuri",
        "Recarmdra",
        "Traesto",
        "Youthful Wind",
        "Dragon Hustle",
        "Burning Petals",
        "The Man's Way",
        "Kamui Miracle",
        "Shield of Justice",
        "Complete Analysis",
        "Blank",
        "ÇƒÇÇÇƒÇÇÇƒÇÇÇƒÇÇÇƒ",
        "100",
        "101",
        "102",
        "Waste Money",
        "Yosuke Strike",
        "Galactic Punt",
        "Fan Assault",
        "Atomic Press",
        "Wild Ways",
        "Ultra Trigger",
        "Galaxy Kick",
        "Full Analysis",
        "Third Eye",
        "Weakness Scan",
        "Healing Wave",
        "Relaxing Wave",
        "Analyze",
        "Summon",
        "Enemy Radar",
        "Treasure Radar",
        "Certain Escape",
        "Myriad Truths",
        "Cavalry Attack",
        "Cavalry Attack",
        "Cavalry Attack",
        "Cavalry Attack",
        "Cavalry Attack",
        "Cavalry Attack",
        "All-Out Boost",
        "Rise's Revival",
        "Stamina Song",
        "Vigor Song",
        "Sarx Drop",
        "Medicine",
        "Medical Powder",
        "Spirit Water",
        "Life Stone",
        "Bead",
        "Value Medicine",
        "Medical Kit",
        "Umugi Water",
        "Bead Chain",
        "Pneuma Drop",
        "Snuff Soul",
        "Chewing Soul",
        "Precious Egg",
        "12E",
        "12F",
        "130",
        "131",
        "132",
        "133",
        "134",
        "135",
        "136",
        "137",
        "138",
        "139",
        "13A",
        "13B",
        "13C",
        "13D",
        "13E",
        "13F",
        "140",
        "141",
        "142",
        "143",
        "144",
        "145",
        "146",
        "147",
        "148",
        "149",
        "14A",
        "14B",
        "14C",
        "14D",
        "14E",
        "14F",
        "150",
        "151",
        "152",
        "153",
        "154",
        "155",
        "156",
        "157",
        "158",
        "159",
        "15A",
        "15B",
        "15C",
        "Junes Bomber",
        "Twin Dragons",
        "Beauty & The Beast",
        "Wind of Oblivion",
        "Bottomless Envy",
        "Burn to Ashes",
        "Shivering Rondo",
        "Summon",
        "Summon",
        "Forbidden Murmur",
        "Roar of Wrath",
        "Fanatical Spark",
        "Supreme Insight",
        "Nihil Hand",
        "Ultra Charge",
        "Nullity Guidance",
        "Attack",
        "Whisper",
        "Chant",
        "Prayer",
        "Character Setup",
        "Command",
        "Command",
        "Command",
        "Command",
        "Command",
        "Command",
        "Element Zero",
        "Mute Ray",
        "Quad Converge",
        "Control",
        "Unerring Justice",
        "Nebula Oculus",
        "Quake",
        "Bewildering Fog",
        "Bewildering Fog",
        "Thousand Curses",
        "World's End",
        "Terror Voice",
        "Control",
        "Fury of Yasogami",
        "Bewildering Fog",
        "Summons to Yomi",
        "Kuro Ikazuchi",
        "Oho Ikazuchi",
        "Megidolaon",
        "Thousand Curses",
        "18C",
        "18D",
        "18E",
        "18F",
        "190",
        "191",
        "192",
        "193",
        "194",
        "195",
        "196",
        "197",
        "198",
        "199",
        "19A",
        "19B",
        "19C",
        "19D",
        "19E",
        "19F",
        "1A0",
        "1A1",
        "1A2",
        "1A3",
        "1A4",
        "1A5",
        "1A6",
        "1A7",
        "1A8",
        "1A9",
        "1AA",
        "1AB",
        "1AC",
        "1AD",
        "1AE",
        "1AF",
        "1B0",
        "1B1",
        "1B2",
        "1B3",
        "1B4",
        "1B5",
        "1B6",
        "1B7",
        "Snow Flower Honey",
        "Revival Rope",
        "Sentou Seed",
        "Sentou Petal",
        "Sentou Fruit",
        "Fire Bell",
        "Ice Bell",
        "Wind Bell",
        "Lightning Bell",
        "Flame Dotaku",
        "Frigid Dotaku",
        "Gale Dotaku",
        "Bolt Dotaku",
        "1C5",
        "1C6",
        "1C7",
        "1C8",
        "1C9",
        "1CA",
        "1CB",
        "1CC",
        "1CD",
        "1CE",
        "1CF",
        "1D0",
        "1D1",
        "1D2",
        "1D3",
        "1D4",
        "1D5",
        "1D6",
        "1D7",
        "Resist Physical",
        "Null Physical",
        "Repel Physical",
        "Absorb Physical",
        "Resist Fire",
        "Null Fire",
        "Repel Fire",
        "Absorb Fire",
        "Resist Ice",
        "Null Ice",
        "Repel Ice",
        "Absorb Ice",
        "Resist Elec",
        "Null Elec",
        "Repel Elec",
        "Absorb Elec",
        "Resist Wind",
        "Null Wind",
        "Repel Wind",
        "Absorb Wind",
        "Resist Light",
        "Null Light",
        "Repel Light",
        "Resist Dark",
        "Null Dark",
        "Repel Dark",
        "Null Panic",
        "Null Exhaust",
        "Null Mute",
        "Null Fear",
        "Null Rage",
        "Null Poison",
        "Null Dizzy",
        "Null Enervate",
        "Unshaken Will",
        "Masakados",
        "Dodge Physical",
        "Evade Physical",
        "Dodge Fire",
        "Evade Fire",
        "Dodge Ice",
        "Evade Ice",
        "Dodge Wind",
        "Evade Wind",
        "Dodge Elec",
        "Evade Elec",
        "Angelic Grace",
        "Fire Boost",
        "Fire Amp",
        "Ice Boost",
        "Ice Amp",
        "Elec Boost",
        "Elec Amp",
        "Wind Boost",
        "Wind Amp",
        "Certain Escape",
        "HP Up 1",
        "HP Up 2",
        "HP Up 3",
        "SP Up 1",
        "SP Up 2",
        "SP Up 3",
        "Counter",
        "Counterstrike",
        "High Counter",
        "Regenerate 1",
        "Regenerate 2",
        "Regenerate 3",
        "Invigorate 1",
        "Invigorate 2",
        "Invigorate 3",
        "Growth 1",
        "Growth 2",
        "Growth 3",
        "Auto-Tarukaja",
        "Auto-Rakukaja",
        "Auto-Sukukaja",
        "Alertness",
        "Sharp Student",
        "Apt Pupil",
        "Ali Dance",
        "Firm Stance",
        "Spell Master",
        "Arms Master",
        "HP Favor",
        "SP Favor",
        "Divine Grace",
        "Endure",
        "Enduring Soul",
        "Survive Light",
        "Survive Dark",
        "Auto-Maraku",
        "Auto-Mataru",
        "Auto-Masuku",
        "Panic Boost",
        "Poison Boost",
        "Exhaust Boost",
        "Silence Boost",
        "Fear Boost",
        "Rage Boost",
        "Dizzy Boost",
        "Enervate Boost",
        "Ailment Boost",
        "Hama Boost",
        "Mudo Boost",
        "Endure Light",
        "Endure Dark",
        "Cool Breeze",
        "Victory Cry",
        "Resist Poison",
        "Resist Panic",
        "Resist Fear",
        "Resist Exhaust",
        "Resist Enervate",
        "Resist Rage",
        "Resist Dizzy",
        "Resist Mute",
        "HP Amp",
        "SP Amp",
        "Fast Heal",
        "Insta-Heal",
        "Infinite Endure",
        "Izanami Endure",
        "Alienation Wall",
        "Blank",
        "Blank",
        "Blank",
        "Blank",
        "Blank",
        "Blank",
        "Blank",
        "Blank",
        "Blank",
        "Blank",
        "Mudo",
        "Blank",
        "Blank",
        "Blank",
        "Blank",
        "Blank",
        "Blank",
        "Blank",
        "Blank",
        "Blank",
        "Blank",
        "Blank",
        "Blank",
        "Blank",
        "Blank",
        "Blank",
        "Blank",
        "Blank",
    ];
    public static ReadOnlyCollection<SkillCatalogEntry> Skills { get; } = CreateIndexedEntries(SkillsNames, static (id, name) => new SkillCatalogEntry((ushort)id, name));
    public static ReadOnlyDictionary<ushort, SkillCatalogEntry> SkillsById { get; } = CreateLookup(Skills, static entry => entry.Id);

}